// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_pecano.Context;

#nullable disable

namespace api_pecano.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api_pecano.Models.TipoTrabajador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TipoTrabajadores");
                });

            modelBuilder.Entity("api_pecano.Models.Trabajador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("diasLaborados")
                        .HasColumnType("int");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("faltas")
                        .HasColumnType("int");

                    b.Property<int>("horasLaboradas")
                        .HasColumnType("int");

                    b.Property<int>("tipoTrabajador")
                        .HasColumnType("int");

                    b.Property<int>("trabajadorid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("trabajadorid");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("api_pecano.Models.Trabajador", b =>
                {
                    b.HasOne("api_pecano.Models.TipoTrabajador", "trabajador")
                        .WithMany()
                        .HasForeignKey("trabajadorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("trabajador");
                });
#pragma warning restore 612, 618
        }
    }
}
